services:
  db:
    image: postgres:15
    container_name: db_rtrw
    environment:
      # Menggunakan variabel dari file .env (yang aman dari Git)
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database/manajemen_rtrw2.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: backend_rtrw
    depends_on:
      - db
    environment:
      # MENGGUNAKAN VARIABEL LINGKUNGAN DARI .env
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: supersecret123
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

volumes:
  db_data: