version: "3.9"
services:
  db:
    image: postgres:15
    container_name: db_rtrw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rtrw
      POSTGRES_DB: manajemen_rtrw2
    ports:
      - "5432:5432"
    volumes:
      - ./database/manajemen_rtrw2.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: backend_rtrw
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:rtrw@db:5432/manajemen_rtrw2
      - JWT_SECRET=supersecret123
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

volumes:
  db_data:
